delete from public.vehicles
where id in (
  '00000000-0000-4000-8000-000000000002',
  '00000000-0000-4000-8000-000000000003'
);

insert into public.vehicles (
  id,
  status,
  make,
  model,
  trim,
  year,
  price,
  mileage,
  transmission,
  fuel,
  body,
  location,
  listed_by,
  quality_score,
  primary_image_url,
  tags,
  inspected,
  featured,
  price_signal,
  exterior_color,
  interior_color,
  engine,
  drivetrain,
  doors,
  seats,
  steering,
  condition,
  availability,
  registration_status,
  import_status,
  ownership_history,
  service_history,
  documents,
  equipment,
  safety,
  inspection
) values
  (
    '00000000-0000-4000-8000-000000000001',
    'published',
    'Toyota',
    'RAV4',
    'Hybrid XLE',
    2021,
    38500000,
    41000,
    'Automatic',
    'Hybrid',
    'SUV',
    'Kigali, Kacyiru',
    'FastDeal Rwanda',
    9.2,
    'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1400&q=80',
    array['Verified details', 'Fresh inspection', 'Popular SUV'],
    true,
    true,
    'Great price',
    'Pearl white',
    'Black cloth',
    '2.5L Hybrid',
    'AWD',
    5,
    5,
    'Left-hand drive',
    'Excellent',
    'Inspection complete',
    'Registered in Rwanda',
    'Japan import',
    'Single owner in Rwanda',
    'Service records available',
    array['Registration card', 'Roadworthiness', 'Insurance copy'],
    array['Reverse camera', 'Bluetooth', 'Cruise control', 'Keyless entry', 'Alloy wheels'],
    array['ABS', 'Airbags', 'Lane assist', 'Stability control'],
    '{
      "mechanical": "Engine and hybrid system checked. Smooth drive with no warning lights.",
      "exterior": "Clean paint with minor everyday marks.",
      "interior": "Well kept cabin and clean dashboard.",
      "tyresAndBrakes": "Tyres in good condition. Brakes inspected.",
      "documents": "Registration details reviewed.",
      "notes": "Strong option for a buyer who wants a modern family SUV."
    }'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000004',
    'published',
    'Nissan',
    'Navara',
    'Double Cab 4x4',
    2022,
    54800000,
    29000,
    'Automatic',
    'Diesel',
    'Pickup',
    'Kigali, Gisozi',
    'FastDeal Rwanda',
    9.1,
    'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1400&q=80',
    array['4x4', 'Work ready', 'Low mileage'],
    true,
    true,
    'New arrival',
    'Grey',
    'Black cloth',
    '2.3L Diesel',
    '4x4',
    4,
    5,
    'Left-hand drive',
    'Excellent',
    'Inspection complete',
    'Registered in Rwanda',
    'South Africa import',
    'Company owned',
    'Service records available',
    array['Registration card', 'Roadworthiness', 'Insurance copy'],
    array['Reverse camera', 'Bed liner', 'Bluetooth', 'Tow hook', 'Alloy wheels'],
    array['ABS', 'Airbags', 'Hill descent control', 'Stability control'],
    '{
      "mechanical": "Diesel engine and 4x4 system checked.",
      "exterior": "Clean body and cargo bed liner fitted.",
      "interior": "Well kept double-cab interior.",
      "tyresAndBrakes": "Good tyres and firm braking.",
      "documents": "Company ownership documents reviewed.",
      "notes": "Strong pickup for business, site visits, and family use."
    }'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000005',
    'published',
    'Hyundai',
    'Kona',
    'Electric',
    2021,
    33700000,
    33000,
    'Automatic',
    'Electric',
    'SUV',
    'Kigali, Kimihurura',
    'FastDeal Rwanda',
    8.9,
    'https://images.unsplash.com/photo-1619405399517-d7fce0f13302?auto=format&fit=crop&w=1400&q=80',
    array['Electric', 'Low running cost', 'Verified details'],
    true,
    false,
    'Fair price',
    'Blue',
    'Black cloth',
    'Electric motor',
    'FWD',
    5,
    5,
    'Left-hand drive',
    'Very good',
    'Available now',
    'Registered in Rwanda',
    'Korea import',
    'Privately owned',
    'Battery health checked',
    array['Registration card', 'Roadworthiness', 'Charging cable'],
    array['Reverse camera', 'Bluetooth', 'Cruise control', 'Keyless entry', 'Touchscreen audio'],
    array['ABS', 'Airbags', 'Lane assist', 'Stability control'],
    '{
      "mechanical": "Electric drivetrain checked and charging cable available.",
      "exterior": "Clean exterior with normal use marks.",
      "interior": "Clean cabin and functional controls.",
      "tyresAndBrakes": "Tyres and regenerative braking checked.",
      "documents": "Registration information reviewed.",
      "notes": "Good choice for buyers who want lower running costs."
    }'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000006',
    'published',
    'Suzuki',
    'Swift',
    'GL',
    2020,
    16500000,
    47000,
    'Automatic',
    'Petrol',
    'Hatchback',
    'Kigali, Nyamirambo',
    'FastDeal Rwanda',
    8.5,
    'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1400&q=80',
    array['Budget friendly', 'City car', 'Easy to park'],
    true,
    false,
    'Great price',
    'Red',
    'Black cloth',
    '1.2L Petrol',
    'FWD',
    5,
    5,
    'Right-hand drive',
    'Good',
    'Available now',
    'Registered in Rwanda',
    'Japan import',
    'Privately owned',
    'Partial service records',
    array['Registration card', 'Roadworthiness'],
    array['Bluetooth', 'Air conditioning', 'Power windows'],
    array['ABS', 'Airbags'],
    '{
      "mechanical": "Engine and gearbox checked for normal operation.",
      "exterior": "Good exterior with minor marks.",
      "interior": "Clean practical cabin.",
      "tyresAndBrakes": "Tyres usable and brakes checked.",
      "documents": "Registration details reviewed.",
      "notes": "Affordable hatchback for city driving."
    }'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000007',
    'published',
    'Toyota',
    'Land Cruiser Prado',
    'TX-L',
    2018,
    68500000,
    72000,
    'Automatic',
    'Diesel',
    'SUV',
    'Kigali, Kibagabaga',
    'FastDeal Rwanda',
    8.8,
    'https://images.unsplash.com/photo-1606220838315-056192d5e927?auto=format&fit=crop&w=1400&q=80',
    array['7 seats', 'Diesel SUV', '4x4'],
    true,
    true,
    'Fair price',
    'White',
    'Beige leather',
    '2.8L Diesel',
    '4x4',
    5,
    7,
    'Right-hand drive',
    'Very good',
    'Viewing by appointment',
    'Registered in Rwanda',
    'Japan import',
    'Privately owned',
    'Service records available',
    array['Registration card', 'Roadworthiness', 'Insurance copy'],
    array['Leather seats', 'Reverse camera', 'Bluetooth', 'Third-row seats', 'Alloy wheels'],
    array['ABS', 'Airbags', 'Stability control', 'Hill assist'],
    '{
      "mechanical": "Diesel engine, gearbox, and 4x4 system checked.",
      "exterior": "Clean body with normal SUV use marks.",
      "interior": "Spacious cabin with clean leather seats.",
      "tyresAndBrakes": "Good tyre condition and braking response.",
      "documents": "Ownership and registration details reviewed.",
      "notes": "Reliable 7-seat SUV for family and upcountry travel."
    }'::jsonb
  ),
  (
    '00000000-0000-4000-8000-000000000008',
    'published',
    'Mazda',
    'CX-5',
    'Skyactiv',
    2020,
    29800000,
    52000,
    'Automatic',
    'Petrol',
    'SUV',
    'Kigali, Gikondo',
    'FastDeal Rwanda',
    8.6,
    'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=1400&q=80',
    array['Family SUV', 'Verified details', 'Comfortable drive'],
    true,
    false,
    'Great price',
    'Deep blue',
    'Black cloth',
    '2.0L Petrol',
    'AWD',
    5,
    5,
    'Right-hand drive',
    'Very good',
    'Available now',
    'Registered in Rwanda',
    'Japan import',
    'Privately owned',
    'Partial service records',
    array['Registration card', 'Roadworthiness'],
    array['Reverse camera', 'Bluetooth', 'Cruise control', 'Push start', 'Alloy wheels'],
    array['ABS', 'Airbags', 'Stability control'],
    '{
      "mechanical": "Engine and gearbox checked. Smooth road test.",
      "exterior": "Good exterior with clean paint.",
      "interior": "Clean cabin and working infotainment.",
      "tyresAndBrakes": "Tyres and brakes checked.",
      "documents": "Registration details reviewed.",
      "notes": "Comfortable mid-size SUV with strong buyer demand."
    }'::jsonb
  )
on conflict (id) do update set
  status = excluded.status,
  make = excluded.make,
  model = excluded.model,
  trim = excluded.trim,
  year = excluded.year,
  price = excluded.price,
  mileage = excluded.mileage,
  transmission = excluded.transmission,
  fuel = excluded.fuel,
  body = excluded.body,
  location = excluded.location,
  listed_by = excluded.listed_by,
  quality_score = excluded.quality_score,
  primary_image_url = excluded.primary_image_url,
  tags = excluded.tags,
  inspected = excluded.inspected,
  featured = excluded.featured,
  price_signal = excluded.price_signal,
  exterior_color = excluded.exterior_color,
  interior_color = excluded.interior_color,
  engine = excluded.engine,
  drivetrain = excluded.drivetrain,
  doors = excluded.doors,
  seats = excluded.seats,
  steering = excluded.steering,
  condition = excluded.condition,
  availability = excluded.availability,
  registration_status = excluded.registration_status,
  import_status = excluded.import_status,
  ownership_history = excluded.ownership_history,
  service_history = excluded.service_history,
  documents = excluded.documents,
  equipment = excluded.equipment,
  safety = excluded.safety,
  inspection = excluded.inspection;
