export type Vehicle = {
  id: string;
  make: string;
  model: string;
  trim: string;
  year: number;
  price: number;
  mileage: number;
  transmission: "Automatic" | "Manual";
  fuel: "Petrol" | "Diesel" | "Hybrid" | "Electric";
  body: "SUV" | "Sedan" | "Hatchback" | "Pickup" | "Van";
  location: string;
  listedBy: string;
  qualityScore: number;
  image: string;
  tags: string[];
  inspected: boolean;
  featured: boolean;
  priceSignal: "Great price" | "Fair price" | "New arrival";
  exteriorColor: string;
  interiorColor: string;
  engine: string;
  drivetrain: "FWD" | "RWD" | "AWD" | "4x4";
  doors: number;
  seats: number;
  steering: "Left-hand drive" | "Right-hand drive";
  condition: "Excellent" | "Very good" | "Good";
  availability: "Available now" | "Inspection complete" | "Viewing by appointment";
  registrationStatus: string;
  importStatus: string;
  ownershipHistory: string;
  serviceHistory: string;
  documents: string[];
  equipment: string[];
  safety: string[];
  inspection: {
    mechanical: string;
    exterior: string;
    interior: string;
    tyresAndBrakes: string;
    documents: string;
    notes: string;
  };
};

export type VehicleRow = {
  id: string;
  make: string;
  model: string;
  trim: string | null;
  year: number;
  price: number;
  mileage: number;
  transmission: Vehicle["transmission"];
  fuel: Vehicle["fuel"];
  body: Vehicle["body"];
  location: string;
  listed_by: string | null;
  quality_score: number | null;
  primary_image_url: string | null;
  tags: string[] | null;
  inspected: boolean | null;
  featured: boolean | null;
  price_signal: Vehicle["priceSignal"] | null;
  exterior_color: string | null;
  interior_color: string | null;
  engine: string | null;
  drivetrain: Vehicle["drivetrain"] | null;
  doors: number | null;
  seats: number | null;
  steering: Vehicle["steering"] | null;
  condition: Vehicle["condition"] | null;
  availability: Vehicle["availability"] | null;
  registration_status: string | null;
  import_status: string | null;
  ownership_history: string | null;
  service_history: string | null;
  documents: string[] | null;
  equipment: string[] | null;
  safety: string[] | null;
  inspection: Partial<Vehicle["inspection"]> | null;
};
